name: 'Ambassador Telepresence Actions'
description: 'Telepresence combined with GitHub Actions allows you to run integration tests in your CI pipeline without having to run any dependant service. By connecting to the target Kubernetes cluster, intercepting traffic to the remote service and sending it to an instance of the service running in CI you will be able to test bugfixes, updates and features very easily.'
branding:
  color: purple
inputs:
  version:
    description: The version of telepresence to use
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: datawire/telepresence-actions
        path: './telepresence-actions'
    - name: Configure Telepresence
      uses: ./telepresence-actions/configuring/
      with:
        version: ${{inputs.version}}