name: 'Telepresence Install'
description: 'Installs an specific version of telepresence'
inputs:
  version:
    description: Version of Telepresence to Install
    required: false
    default: latest
  actionVersion:
    description: Version of Telepresence to Install
    required: false
    default: ${{ github.action_ref }}
runs:
  using: 'node16'
  pre: 'pre-install.js'
  main: 'install.js'
